---Farmers Table
CREATE TABLE Farmers (
    Farmer_ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    First_Name VARCHAR2(50) NOT NULL,
    Last_Name VARCHAR2(50) NOT NULL,
    Phone_Number VARCHAR2(15) UNIQUE,
    District VARCHAR2(50) NOT NULL,
    Registration_Date DATE DEFAULT SYSDATE
);

--Batches Table (For Grouping Deliveries)
CREATE TABLE Batches (
    Batch_ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Batch_Name VARCHAR2(50) NOT NULL,
    Created_Date DATE DEFAULT SYSDATE
);

--Deliveries Table (Tracks incoming coffee cherries)
CREATE TABLE Deliveries (
    Delivery_ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Farmer_ID NUMBER REFERENCES Farmers(Farmer_ID) ON DELETE CASCADE,
    Batch_ID NUMBER REFERENCES Batches(Batch_ID),
    Weight_Kg NUMBER(10,2) NOT NULL CONSTRAINT check_positive_weight CHECK (Weight_Kg > 0),
    Quality_Grade CHAR(1) CONSTRAINT check_grade CHECK (Quality_Grade IN ('A', 'B', 'C')),
    Delivery_Date DATE DEFAULT SYSDATE
);

---Processing Table (Tracks milling stages)
CREATE TABLE Processing (
    Process_ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Batch_ID NUMBER REFERENCES Batches(Batch_ID),
    Stage VARCHAR2(30) CONSTRAINT check_stage CHECK (Stage IN ('Washing', 'Drying', 'Milling', 'Ready')),
    Status VARCHAR2(20) DEFAULT 'Pending',
    Last_Updated DATE DEFAULT SYSDATE
);

---Payouts Table (Calculates financial payments to farmers)
CREATE TABLE Payouts (
    Payout_ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Delivery_ID NUMBER REFERENCES Deliveries(Delivery_ID) ON DELETE CASCADE,
    Amount_RWF NUMBER(12,2) NOT NULL,
    Payment_Status VARCHAR2(20) DEFAULT 'Pending' CONSTRAINT check_payout_status CHECK (Payment_Status IN ('Pending', 'Approved', 'Paid')),
    Payout_Date DATE
);

--Public Holidays Reference Table (For temporal restriction triggers)
CREATE TABLE Public_Holidays (
    Holiday_Date DATE PRIMARY KEY,
    Holiday_Name VARCHAR2(100) NOT NULL
);


--Audit Log Table (For security/history tracking)

CREATE TABLE Audit_Log (
    Audit_ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Table_Name VARCHAR2(50),
    Action VARCHAR2(10),
    User_Executed VARCHAR2(50),
    Action_Timestamp TIMESTAMP DEFAULT SYSTIMESTAMP,
    Details VARCHAR2(4000)
);


---Public Holidays (Rwanda Holidays)
INSERT INTO Public_Holidays (Holiday_Date, Holiday_Name) VALUES (TO_DATE('2026-01-01', 'YYYY-MM-DD'), 'New Year');
INSERT INTO Public_Holidays (Holiday_Date, Holiday_Name) VALUES (TO_DATE('2026-04-07', 'YYYY-MM-DD'), 'Genocide Memorial Day');
INSERT INTO Public_Holidays (Holiday_Date, Holiday_Name) VALUES (TO_DATE('2026-07-01', 'YYYY-MM-DD'), 'Independence Day');

----Farmers
INSERT INTO Farmers (First_Name, Last_Name, Phone_Number, District) VALUES ('Jean', 'Ndayisenga', '+250788123456', 'Huye');
INSERT INTO Farmers (First_Name, Last_Name, Phone_Number, District) VALUES ('Marie', 'Uwimana', '+250788654321', 'Gakenke');


---Batches
INSERT INTO Batches (Batch_Name) VALUES ('Huye_WetMill_Batch_01');

COMMIT;


----(Procedures, Functions, and Packages)--


----Package Specification
CREATE OR REPLACE PACKAGE pkg_coffee_mgmt AS
    -- Function to calculate cherry price based on grade and weight
    FUNCTION calculate_price(p_weight IN NUMBER, p_grade IN CHAR) RETURN NUMBER;
    
    -- Procedure to register delivery and automatically schedule a payout
    PROCEDURE register_delivery(
        p_farmer_id IN NUMBER,
        p_batch_id IN NUMBER,
        p_weight IN NUMBER,
        p_grade IN CHAR
    );
END pkg_coffee_mgmt;
/

----Package Body--
CREATE OR REPLACE PACKAGE BODY pkg_coffee_mgmt AS

    FUNCTION calculate_price(p_weight IN NUMBER, p_grade IN CHAR) RETURN NUMBER IS
        v_price_per_kg NUMBER;
    BEGIN
        -- Standardize pricing models per grade in RWF
        IF p_grade = 'A' THEN
            v_price_per_kg := 410;
        ELSIF p_grade = 'B' THEN
            v_price_per_kg := 320;
        ELSE
            v_price_per_kg := 200;
        END IF;
        
        RETURN p_weight * v_price_per_kg;
    EXCEPTION
        WHEN OTHERS THEN
            RETURN 0;
    END calculate_price;

    PROCEDURE register_delivery(
        p_farmer_id IN NUMBER,
        p_batch_id IN NUMBER,
        p_weight IN NUMBER,
        p_grade IN CHAR
    ) IS
        v_delivery_id NUMBER;
        v_calculated_payout NUMBER;
    BEGIN
        -- Step 1: Insert Delivery
        INSERT INTO Deliveries (Farmer_ID, Batch_ID, Weight_Kg, Quality_Grade)
        VALUES (p_farmer_id, p_batch_id, p_weight, p_grade)
        RETURNING Delivery_ID INTO v_delivery_id;
        
        -- Step 2: Calculate payment amount using our package function
        v_calculated_payout := calculate_price(p_weight, p_grade);
        
        -- Step 3: Insert Pending Payout Record
        INSERT INTO Payouts (Delivery_ID, Amount_RWF, Payment_Status)
        VALUES (v_delivery_id, v_calculated_payout, 'Pending');
        
        COMMIT;
        DBMS_OUTPUT.PUT_LINE('Success: Delivery recorded and Payout of ' || v_calculated_payout || ' RWF initialized.');
    EXCEPTION
        WHEN OTHERS THEN
            ROLLBACK;
            DBMS_OUTPUT.PUT_LINE('Transaction Failed: Rolling back database changes.');
            RAISE;
    END register_delivery;

END pkg_coffee_mgmt;
/


----Test the Package

---Execute Delivery Registration (Farmer ID: 1, Batch: 1, Weight: 150.5kg, Grade: A)
SET SERVEROUTPUT ON;
BEGIN
    pkg_coffee_mgmt.register_delivery(
        p_farmer_id => 1,
        p_batch_id  => 1,
        p_weight    => 150.5,
        p_grade     => 'A'
    );
END;
/

-----Temporal Constraints Trigger--
--System Security Trigger
CREATE OR REPLACE TRIGGER trg_restrict_operations
BEFORE INSERT OR UPDATE OR DELETE ON Payouts
DECLARE
    v_day VARCHAR2(10);
    v_is_holiday NUMBER;
BEGIN
    -- Extract the day of the week
    v_day := TO_CHAR(SYSDATE, 'DY', 'NLS_DATE_LANGUAGE=ENGLISH');
    
    -- Check if today is registered in our Holiday table
    SELECT COUNT(*) INTO v_is_holiday 
    FROM Public_Holidays 
    WHERE TRUNC(Holiday_Date) = TRUNC(SYSDATE);

    -- Block transactions on Weekends OR Public Holidays
    IF v_day IN ('SAT', 'SUN') OR v_is_holiday > 0 THEN
        raise_application_error(-20001, 'Unauthorized operation: Database modifications are blocked on weekends and public holidays.');
    END IF;
END;
/

---Audit Trail Trigger (User Activity Tracking)--
CREATE OR REPLACE TRIGGER trg_audit_payout_updates
AFTER UPDATE OF Payment_Status ON Payouts
FOR EACH ROW
BEGIN
    INSERT INTO Audit_Log (Table_Name, Action, User_Executed, Details)
    VALUES (
        'PAYOUTS',
        'UPDATE',
        USER,
        'Payout ID ' || :OLD.Payout_ID || ' status changed from ' || :OLD.Payment_Status || ' to ' || :NEW.Payment_Status
    );
END;
/

---payout status
UPDATE Payouts 
SET Payment_Status = 'Approved' 
WHERE Payout_ID = 1;

-- Run: Query the Audit Log to prove activity tracking
SELECT * FROM Audit_Log;


--View for Dashboard Visualizations--

CREATE OR REPLACE VIEW vw_cooperative_dashboard AS
SELECT 
    f.District,
    f.First_Name || ' ' || f.Last_Name AS Farmer_Name,
    SUM(d.Weight_Kg) AS Total_Delivered_Kg,
    AVG(d.Weight_Kg) AS Average_Delivery_Size,
    SUM(p.Amount_RWF) AS Total_Earnings_RWF,
    COUNT(d.Delivery_ID) AS Total_Deliveries
FROM Farmers f
JOIN Deliveries d ON f.Farmer_ID = d.Farmer_ID
JOIN Payouts p ON d.Delivery_ID = p.Delivery_ID
GROUP BY f.District, f.First_Name, f.Last_Name;


--Verify that the record was correctly written to both the Deliveries and Payouts tables:
SELECT d.Delivery_ID, f.First_Name, f.Last_Name, d.Weight_Kg, d.Quality_Grade, p.Amount_RWF, p.Payment_Status
FROM Deliveries d
JOIN Farmers f ON d.Farmer_ID = f.Farmer_ID
JOIN Payouts p ON d.Delivery_ID = p.Delivery_ID;



UPDATE Payouts 
SET Payment_Status = 'Approved' 
WHERE Payout_ID = 1;

---prove that the trigger captured the change automatically:
SELECT Audit_ID, Table_Name, Action, User_Executed, Details, Action_Timestamp 
FROM Audit_Log;


--Check that both objects compiled successfully without errors--
SELECT object_name, object_type, status 
FROM user_objects 
WHERE object_name = 'PKG_COFFEE_MGMT';

----Initialize the processing record when a batch is created
INSERT INTO Processing (Batch_ID, Stage, Status)
VALUES (1, 'Washing', 'In-Progress');

----Update the processing stage as the batch moves to the drying beds
UPDATE Processing 
SET Stage = 'Drying', 
    Status = 'In-Progress', 
    Last_Updated = SYSDATE 
WHERE Batch_ID = 1;

----View current active processing bottlenecks in the cooperative
SELECT Batch_ID, Stage, Status, Last_Updated 
FROM Processing 
WHERE Status != 'Completed';

select * from batches;



